backend:
  # name: test-repo
  name: git-gateway
  repo: ALLC84/my-notes-vuepress
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin

media_folder: "docs/.vuepress/public/images/"
public_folder: "/images"

publish_mode: editorial_workflow

site_url: https://codenotes.netlify.app/
display_url: https://codenotes.netlify.app/


collections:
  - name: "notes" # Used in routes, e.g., /admin/collections/blog
    label: "Notes" # Used in the UI
    lang: es
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    show_preview_links: true
    preview_path: "{{slug}}/"
    folder: "docs/" # The path to the folder where the documents are stored
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Image", name: "image", widget: "image", media_library: {config: {multiple: false}}}
      - {label: "Body", name: "body", widget: "markdown"}


  - name: 'settings' # all the things in one entry, for documentation and quick testing
    label: 'Settings'
    folder: 'docs/.vuepress/public/data'
    file: 'docs/.vuepress/public/data/data.json'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }   

      - label: 'Typed List'
        name: 'typed_list'
        widget: 'list'
        types:
          - label: 'Card'
            name: 'card'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'string' }
              - { label: 'Path', name: 'path', widget: 'string' }
              - { label: 'Image', name: 'image', widget: 'image' }
          - label: 'Type 2 Object'
            name: 'type_2_object'
            widget: 'object'
            fields:
              - { label: 'Number', name: 'number', widget: 'number' }
              - { label: 'Select', name: 'select', widget: 'select', options: ['a', 'b', 'c'] }
              - { label: 'Datetime', name: 'datetime', widget: 'datetime' }
              - { label: 'Markdown', name: 'markdown', widget: 'markdown' }
