backend:
  name: github
  repo: ALLC84/my-notes-vuepress
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin

media_folder: ".vuepress/public/images"
public_folder: "/images"

# site_url: https://notes-alex.netlify.com
# display_url: https://notes-alex.netlify.com


collections:
  - name: "notes" # Used in routes, e.g., /admin/collections/blog
    label: "Notes" # Used in the UI
    folder: "{{slug}}" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    show_preview_links: true
    preview_path: "{{slug}}/README.md"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}