backend:
  # name: test-repo
  name: git-gateway
  repo: ALLC84/my-notes-vuepress
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin

media_folder: "docs/.vuepress/public/images/"
public_folder: "/images"

publish_mode: editorial_workflow

site_url: https://codenotes.netlify.app/
display_url: https://codenotes.netlify.app/


collections:
  # EDIT HOME PAGE
  - name: 'home' # all the things in one entry, for documentation and quick testing
    label: 'Home Page'
    folder: 'docs/'
    file: 'docs/README.md'
    create: false
    layout: HomeLayout
    lang: es
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }   
      - { label: 'Description', name: 'description', widget: 'string' }   

      - label: 'Cards'
        name: 'cards'
        widget: 'list'
        types:
          - label: 'Card'
            name: 'card'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'string' }
              - { label: 'Path', name: 'path', widget: 'string' }
              - { label: 'Image', name: 'image', widget: 'image' }


  # CREATE AND EDIT PAGES/NOTES
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    lang: es
    sidebar: auto
    slug: "notas/{{slug}}"
    create: true # Allow users to create new documents in this collection
    folder: "docs/notas" # The path to the folder where the documents are stored
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}


  # JSON SETTING BUTTON LINKS
  - name: "settings"
    label: "Settings"
    files:
      - file: "docs/.vuepress/public/settings/data-button-select.json"
        label: "Button Links"
        name: "links"
        extension: "json"
        editor:
          preview: false

        fields: 
          - name: listlinks
            label: List Links
            widget: list
            fields:
              - { label: 'Text', name: 'text', widget: 'string' }
              - { label: 'Link', name: 'link', widget: 'string' }
