backend:
  # name: test-repo
  name: git-gateway
  repo: ALLC84/my-notes-vuepress
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin

media_folder: "docs/.vuepress/public/images/"
public_folder: "../../"

# site_url: https://notes-alex.netlify.com
# display_url: https://notes-alex.netlify.com


collections:
  - name: "notes" # Used in routes, e.g., /admin/collections/blog
    label: "Notes" # Used in the UI
    slug: "{{slug}}"
    folder: "{{fields.slug}}" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    show_preview_links: true
    preview_path: "{{fields.slug}}/README.md"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}